[package]
name = "app-a"
version = "0.1.0"
edition = "2021"


[dependencies]
clap = { version = "4.3.5", features = ["derive", "env"] }
twelf = { version="0.11.0", features = ["yaml"]}
thiserror= "1.0.40"
tokio = { version = "1.28.2", features = ["full"] }
serde = "1.0.164"
serde_json = "1.0.97"
log = { version = "0.4.19", features = ["kv_unstable_serde"], default-features = false }
structured-logger="1.0.1"


